baseURL = "/" # base url update
languageCode = "en-us"
title = "best influencer marketing platform india"

############################## navigation ###############################
[menu]

  
[params]
logo = "/images/hearandclear.png"

[[params.apps]]
title = "googlePlay"
url = "https://play.google.com/store/apps/details?id=com.hearandclear.android"
image= "/images/playstore.png"

[[params.apps]]
title = "IOSapp"
url = "https://apps.apple.com/in/app/hearandclear/id1561400242"
image= "/images/appstore.png"

  
  

  
 










